name: 'html-reporter-aws-s3-website'
description: 'HTML Test Results with history to publish to AWS S3 Bucket'
author: 'Pavan Mudigonda'
branding:
  icon: 'layout'
  color: 'green'
inputs:
  test_results:
    description: 'test result data dir'
    required: true
    default: 'test-results'
  results_history:
    description: 'Folder for results history'
    required: true
    default: 'results-history'
  keep_reports:
    description: 'Keep X last reports'
    required: false
    default: '20'    
  github_run_num:
    description: 'GitHub Actions build number'
    required: true
    default: ${{ github.run_number }}
  github_run_id:
    description: 'GitHub Actions run id'
    required: true
    default: ${{ github.run_id }}
  report_url:
    description: 'Use a custom URL instead of *.github.io'
    required: false
    default: ''
  filename:
    description: 'file name with output'
    required: false
    default: 'output.md'
runs:
  using: 'docker'
  image: 'Dockerfile'
