name: test

on:
  workflow_dispatch:

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git Repo
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Create Playwright Test Results History
        uses: PavanMudigonda/playwright-html-reporter-s3-website@v0.2
        id: test-report
        with:
          report_url: http://cicd-devops-mudigonda.s3-website-us-east-1.amazonaws.com
          playwright_results: test-results
          playwright_history: playwright-history
          keep_reports: 1
          args: --acl public-read --follow-symlinks
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-west-1'   # optional: defaults to us-east-1
          SOURCE_DIR: 'playwright-history'      # optional: defaults to entire repository
          # DEST_DIR: ${{ env.GITHUB_RUN_NUMBER }}
          
      - name: Post the link to the report
        if: always()
        uses: Sibz/github-status-action@v1
        with: 
            authToken: ${{secrets.GITHUB_TOKEN}}
            context: 'Test Results Link'
            state: 'success'
            sha: ${{ github.sha }}
            target_url: http://cicd-devops-mudigonda.s3-website-us-east-1.amazonaws.com/${{ github.run_number }}/index.html
